name: Deploy Next.js via Docker

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: self-hosted 

    steps:
      - name: 📥 Ambil Kode Terbaru dari GitHub
        uses: actions/checkout@v4
      - name: 🐳 Rebuild & Restart Docker Container
        # Karena runner berjalan sebagai 'runner-user', pastikan user tersebut 
        # sudah memiliki izin untuk menjalankan perintah docker tanpa sudo.
        run: |
          # 1. Timpa kode lama di /opt/bnet/ dengan kode terbaru dari GitHub
          rsync -av --exclude='.git' ./ /opt/bnet/
            
          # 2. Pindah ke direktori kerja Anda
          cd /opt/bnet/
            
          # 3. Eksekusi Docker
          docker-compose down
            
          export $(grep -v '^#' .env | xargs) && \
          docker-compose build \
            --build-arg NEXT_PUBLIC_SUPABASE_URL="${NEXT_PUBLIC_SUPABASE_URL}" \
            --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY="${NEXT_PUBLIC_SUPABASE_ANON_KEY}
            
          docker-compose up -d
